import { MentorConfig } from "./types";

/**
 * Placeholder mentor config with generic trading content.
 * Replace with real mentor data when onboarding clients.
 */
export const sampleMentor: MentorConfig = {
  id: "sample-mentor",
  displayName: "Sample Mentor",
  branding: {
    primaryColor: "#2dd98f",
    accentColor: "#f0a500",
  },

  terms: [
    { term: "SUPPORT", definition: "A price level where buying pressure prevents further decline", category: "Technical Analysis" },
    { term: "RESISTANCE", definition: "A price level where selling pressure prevents further rise", category: "Technical Analysis" },
    { term: "BREAKOUT", definition: "Price moving beyond a defined support or resistance level", category: "Technical Analysis" },
    { term: "PULLBACK", definition: "A temporary reversal in the direction of a prevailing trend", category: "Price Action" },
    { term: "LIQUIDITY", definition: "The ease with which an asset can be bought or sold without affecting its price", category: "Market Structure" },
    { term: "SPREAD", definition: "The difference between the bid and ask price", category: "Order Flow" },
    { term: "LEVERAGE", definition: "Using borrowed capital to increase the potential return of an investment", category: "Risk Management" },
    { term: "DRAWDOWN", definition: "The peak-to-trough decline during a specific period of an investment", category: "Risk Management" },
    { term: "CONFLUENCE", definition: "Multiple technical factors aligning at the same price level", category: "Technical Analysis" },
    { term: "DIVERGENCE", definition: "When price and an indicator move in opposite directions", category: "Technical Analysis" },
    { term: "VOLUME", definition: "The number of shares or contracts traded in a given period", category: "Market Data" },
    { term: "ENGULFING", definition: "A candlestick pattern where the body fully covers the previous candle", category: "Candlestick Patterns" },
    { term: "PINBAR", definition: "A candle with a long wick showing rejection of a price level", category: "Candlestick Patterns" },
    { term: "STOPRUN", definition: "A move designed to trigger stop losses before reversing", category: "Market Structure" },
    { term: "FIBONACCI", definition: "Retracement levels based on key ratios used to identify potential reversals", category: "Technical Analysis" },
  ],

  concepts: [
    { label: "Trade with the trend", isValid: true, explanation: "Always align trades with the higher timeframe direction" },
    { label: "Risk 50% per trade", isValid: false, explanation: "Risking 50% per trade is reckless — standard is 1-2%" },
    { label: "Wait for confirmation", isValid: true, explanation: "Enter only after a confirmation candle validates the setup" },
    { label: "Chase extended moves", isValid: false, explanation: "Entering late after a big move increases risk of reversal" },
    { label: "Use a stop loss", isValid: true, explanation: "Every trade must have a predefined stop loss for risk management" },
    { label: "Average down on losers", isValid: false, explanation: "Adding to losing positions compounds risk exposure" },
    { label: "Check higher timeframe", isValid: true, explanation: "Always confirm the higher timeframe trend before entering" },
    { label: "Trade during news", isValid: false, explanation: "News events create unpredictable volatility — avoid unless planned" },
    { label: "Minimum 1:2 risk reward", isValid: true, explanation: "Only take trades with at least 2x the reward vs risk" },
    { label: "Revenge trade after loss", isValid: false, explanation: "Emotional trading after a loss leads to compounding losses" },
    { label: "Journal every trade", isValid: true, explanation: "Recording trades builds accountability and reveals patterns" },
    { label: "Ignore the spread", isValid: false, explanation: "The spread directly impacts entry and profitability" },
    { label: "Wait for key levels", isValid: true, explanation: "Trade at significant support/resistance, not in no-mans land" },
    { label: "Overtrade for volume", isValid: false, explanation: "Quality setups over quantity — overtrading erodes edge" },
    { label: "Follow your plan", isValid: true, explanation: "Stick to the system. Deviation leads to inconsistency" },
    { label: "Trade every session", isValid: false, explanation: "Not every session has valid setups — patience is key" },
  ],

  rules: [
    { rule: "Always identify the higher timeframe trend first", description: "The HTF trend determines trade direction", isTrue: true },
    { rule: "It is okay to enter without a stop loss", description: "Stop losses are optional for experienced traders", isTrue: false },
    { rule: "Price must be at a key level before entry", description: "Key levels provide the highest probability entries", isTrue: true },
    { rule: "A confirmation candle is needed before entry", description: "The confirmation validates that the level is holding", isTrue: true },
    { rule: "You should risk more on high-conviction trades", description: "Increasing size on conviction trades boosts returns", isTrue: false },
    { rule: "Risk no more than 1-2% per trade", description: "Consistent position sizing protects your capital", isTrue: true },
    { rule: "Multiple timeframe confluence improves probability", description: "When levels align across timeframes, probability increases", isTrue: true },
    { rule: "Market structure breaks signal trend changes", description: "A break of structure indicates a potential reversal", isTrue: true },
    { rule: "You can ignore volume in forex", description: "Volume is irrelevant in decentralized markets", isTrue: false },
    { rule: "Move stop to breakeven after 1R profit", description: "Protecting capital after the trade moves in your favor", isTrue: true },
  ],

  gbQuizItems: [
    { value: "00", category: "gb",      hint: ":00 is a primary GB number — strong institutional reference" },
    { value: "05", category: "neither", hint: ":05 is not a recognised GB or CE value" },
    { value: "10", category: "gb",      hint: ":10 is a GB number used in the base algorithm" },
    { value: "15", category: "gb",      hint: ":15 is a primary GB number — quarter-hour boundary" },
    { value: "20", category: "ce",      hint: ":20 is a CE extension of the :10 GB number" },
    { value: "25", category: "neither", hint: ":25 is not a recognised GB or CE value" },
    { value: "30", category: "gb",      hint: ":30 is a primary GB number — half-hour boundary" },
    { value: "35", category: "neither", hint: ":35 is not a recognised GB or CE value" },
    { value: "40", category: "ce",      hint: ":40 is a CE extension of the :30 GB number" },
    { value: "45", category: "gb",      hint: ":45 is a primary GB number — three-quarter-hour boundary" },
    { value: "50", category: "ce",      hint: ":50 is a CE extension of the :40 CE number" },
    { value: "55", category: "neither", hint: ":55 is not a recognised GB or CE value" },
    { value: "02", category: "neither", hint: ":02 is not a recognised GB or CE value" },
    { value: "07", category: "neither", hint: ":07 is not a recognised GB or CE value" },
    { value: "12", category: "ce",      hint: ":12 is a CE extension off the :10 sequence" },
    { value: "17", category: "neither", hint: ":17 is not a recognised GB or CE value" },
    { value: "22", category: "ce",      hint: ":22 is a CE extension of the :20 value" },
    { value: "27", category: "neither", hint: ":27 is not a recognised GB or CE value" },
    { value: "32", category: "ce",      hint: ":32 is a CE extension of the :30 GB number" },
    { value: "37", category: "neither", hint: ":37 is not a recognised GB or CE value" },
    { value: "42", category: "ce",      hint: ":42 is a CE extension of the :40 value" },
    { value: "47", category: "neither", hint: ":47 is not a recognised GB or CE value" },
    { value: "52", category: "ce",      hint: ":52 is a CE extension of the :50 value" },
    { value: "57", category: "neither", hint: ":57 is not a recognised GB or CE value" },
  ],

  cePairings: [
    { gbNumber: "00", ceNumber: "10",  explanation: ":00 pairs with :10 — first CE extension off the hour" },
    { gbNumber: "00", ceNumber: "20",  explanation: ":00 also pairs with :20 — second CE extension" },
    { gbNumber: "15", ceNumber: "25",  explanation: ":15 pairs with :25 — CE extension off the quarter" },
    { gbNumber: "30", ceNumber: "40",  explanation: ":30 pairs with :40 — CE extension off the half-hour" },
    { gbNumber: "30", ceNumber: "50",  explanation: ":30 also pairs with :50 — second CE extension" },
    { gbNumber: "45", ceNumber: "55",  explanation: ":45 pairs with :55 — CE extension off three-quarter" },
    { gbNumber: "10", ceNumber: "20",  explanation: ":10 pairs with :20 as its primary CE counterpart" },
    { gbNumber: "40", ceNumber: "50",  explanation: ":40 pairs with :50 as its primary CE counterpart" },
  ],

  algoItems: [
    { number: "00", algo: "algo1", note: ":00 is exclusively Algo 1 — the primary hourly reference" },
    { number: "15", algo: "algo1", note: ":15 is exclusively Algo 1 — quarter-hour primary" },
    { number: "30", algo: "both",  note: ":30 appears in both Algo 1 and Algo 2 depending on session" },
    { number: "45", algo: "algo2", note: ":45 is exclusively Algo 2 — three-quarter reference" },
    { number: "10", algo: "algo1", note: ":10 belongs to Algo 1 as a secondary reference" },
    { number: "20", algo: "algo2", note: ":20 belongs to Algo 2 as a secondary reference" },
    { number: "40", algo: "both",  note: ":40 can belong to either algorithm — context dependent" },
    { number: "50", algo: "algo2", note: ":50 belongs to Algo 2 as a secondary reference" },
    { number: "05", algo: "algo1", note: ":05 is an Algo 1 minor reference point" },
    { number: "35", algo: "algo2", note: ":35 is an Algo 2 minor reference point" },
    { number: "55", algo: "both",  note: ":55 straddles both algorithms near the hour boundary" },
    { number: "25", algo: "algo1", note: ":25 is an Algo 1 secondary extension" },
  ],

  clockwisePaths: [
    { from: "00", to: ["10", "15"],      note: "From :00 you can flow to :10 (CE) or :15 (next GB)" },
    { from: "10", to: ["20", "15"],      note: "From :10 CE you flow to :20 (CE) or back toward :15 GB" },
    { from: "15", to: ["25", "30"],      note: "From :15 you can flow to :25 (CE) or :30 (next GB)" },
    { from: "30", to: ["40", "45"],      note: "From :30 you can flow to :40 (CE) or :45 (next GB)" },
    { from: "40", to: ["50", "45"],      note: "From :40 CE you flow to :50 (CE) or toward :45 GB" },
    { from: "45", to: ["55", "00"],      note: "From :45 you can flow to :55 (CE) or :00 (next GB hour)" },
    { from: "20", to: ["30", "25"],      note: "From :20 CE you flow to :30 (next GB) or :25" },
    { from: "50", to: ["00", "55"],      note: "From :50 CE you flow to next :00 (GB) or :55" },
  ],
};
